library/config/routes.rb
Rails.application.routes.draw do

  resources :books
  resources :locations

  root to: redirect('/books')
end

library/app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :location, foreign_key: :location
end

library/app/models/location.rb
class Location < ActiveRecord::Base
  has_many :books
end

library/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_book
    @book = Book.find(params[:id])
  end

  def current_location
    @location = Location.find(params[:id])
  end
end

library/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :current_book, only: %i[edit show]

  def index
    @books = Book.all
  end

  def edit; end

  def show; end

  def update
    update_book! Book.find(params[:id])

    redirect_to books_path
  end

  def create
    update_book! Book.new

    redirect_to books_path
  end

  private

  def update_book!(book)
    update_params = params.permit :title, :author, :isbn
    book.update update_params

    book.location = Location.find(params[:location])
    book.style = params[:style]
    book.save!
  end
end

library/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :current_location, only: %i[edit show]

  def index
    @locations = Location.all
  end

  def edit; end

  def show; end

  def update
    update_location! Location.find(params[:id])

    redirect_to locations_path
  end

  def create
    update_location! Location.new

    redirect_to locations_path
  end

  private

  def update_location!(location)
    location.name = params[:name]
    location.is_active = params[:is_active] == 'on'
    location.save!
  end
end

library/app/helpers/application_helper.rb
module ApplicationHelper
end

library/app/helpers/books_helper.rb
module BooksHelper
end

library/app/helpers/locations_helper.rb
module LocationsHelper
end

library/app/views/application/_footer.html.erb
<footer class="footer">

</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

library/app/views/application/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Library</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><%= link_to 'Könyvek', books_path %></li>
      <li><%= link_to 'Helyek', locations_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>

library/app/views/books/edit.html.erb
<div class="uk-container-center uk-panel uk-panel-box">
  <%= form_tag book_path(@book), method: :put, html: { class: 'uk-form' } do %>
    <div class="uk-text-center">
      <div class="uk-grid">
        <div class="uk-width-1-1">
          <div class="uk-form-row">
            <%= label_tag :title, 'Cím:' %>
            <%= text_field_tag :title, @book.title %>
          </div>
          <div class="uk-form-row">
            <%= label_tag :author, 'Szerzők:' %>
            <%= text_field_tag :author, @book.author %>
          </div>
          <div class="uk-form-row">
            <%= label_tag :isbn, 'ISBN:' %>
            <%= text_field_tag :isbn, @book.isbn %>
          </div>
          <div class="uk-form-row">
            <%= label_tag :location, 'helye' %>
            <%= select_tag :location, options_for_select( Location.all.collect {|l| [l.name, l.id]} ) %>
          </div>
          <div class="uk-form-row">
            <%= label_tag :style, 'Stílus' %>
            <%= select_tag :style, options_for_select(Rails.configuration.x.styles.invert, @book.style ) %>
          </div>
          <div class="uk-form-row">
            <%= submit_tag 'Mentés', class: 'uk-button'  %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

library/app/views/books/index.html.erb
<table>
  <thead>
    <tr>
      <th>Cím</th>
      <th>Szerzők</th>
      <th>ISBN</th>
      <th>helye</th>
      <th>stílus</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book|  %>
    <tr>
      <td><%= link_to book.title, book_path(book) %></td>
      <td><%= book.author %></td>
      <td><%= book.isbn %></td>
      <td><%= link_to book.location.name, location_path(book.location) %></td>
      <td><%= Rails.configuration.x.styles[book.style] %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Új', new_book_path, class: 'uk-button'  %>

library/app/views/books/new.html.erb
<div class="uk-container-center uk-panel uk-panel-box">
  <%= form_tag books_path, method: :post, html: { class: 'uk-form' } do %>
    <div class="uk-text-center">
      <div class="uk-grid">
        <div class="uk-width-1-1">
          <div class="uk-form-row">
            <%= label_tag :title, 'Cím:' %>
            <%= text_field_tag :title, 'Cím' %>
          </div>
          <div class="uk-form-row">
            <%= label_tag :author, 'Szerzők:' %>
            <%= text_field_tag :author, 'Szerzo' %>
          </div>
          <div class="uk-form-row">
            <%= label_tag :isbn, 'ISBN:' %>
            <%= text_field_tag :isbn, 'ABC1313131' %>
          </div>
          <div class="uk-form-row">
            <%= label_tag :location, 'helye' %>
            <%= select_tag :location, options_for_select( Location.all.collect {|l| [l.name, l.id]} ) %>
          </div>
          <div class="uk-form-row">
            <%= label_tag :style, 'Stílus' %>
            <%= select_tag :style, options_for_select(Rails.configuration.x.styles.invert) %>
          </div>
          <div class="uk-form-row">
            <%= submit_tag 'Tovább', class: 'uk-button'  %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

library/app/views/books/show.html.erb
<h1> A /<%= @book.title %>/ könyv adatai </h1>

<div class="uk-container-center uk-panel uk-panel-box">
  <div class="uk-text-center">
    <div class="uk-grid">
      <div class="uk-width-1-1">
        <div class="uk-form-row">
          <%= label_tag :title, 'Cím:' %>
          <%= label_tag :title, @book.title %>
        </div>
        <div class="uk-form-row">
          <%= label_tag :author, 'Szerzők:' %>
          <%= label_tag :author, @book.author %>
        </div>
        <div class="uk-form-row">
          <%= label_tag :isbn, 'ISBN:' %>
          <%= label_tag :isbn, @book.isbn %>
        </div>
        <div class="uk-form-row">
          <%= label_tag :location, 'helye:' %>
          <%= link_to @book.location.name, location_path(@book.location) %>
        </div>
        <div class="uk-form-row">
          <%= label_tag :style, 'Stílus:' %>
          <%= label_tag :style, Rails.configuration.x.styles[@book.style] %>
        </div>
        <div class="uk-form-row">
          <%= link_to 'Szerkesztés', edit_book_path(@book), class: 'uk-button'  %>
        </div>
      </div>
    </div>
  </div>
</div>

library/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Library</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

</head>

<body>

  <%= render 'navbar' %>

  <div class="container container-center">
    <%= yield %>
  </div>

  <%= render 'footer' %>
</body>

</html>

library/app/views/locations/edit.html.erb
<div class="uk-container-center uk-panel uk-panel-box">
  <%= form_tag location_path(@location), method: :put, html: { class: 'uk-form' } do %>
    <div class="uk-text-center">
      <div class="uk-grid">
        <div class="uk-width-1-1">
          <div class="uk-form-row">
            <%= label_tag :name, 'Cím:' %>
            <%= text_field_tag :name, @location.name %>
          </div>
          <div class="uk-form-row">
            <%= label_tag :is_active, 'Aktív:' %>
            <%= check_box_tag :is_active, nil, @location.is_active %>
          </div>
          <div class="uk-form-row">
            <%= submit_tag 'Mentés', class: 'uk-button'  %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

library/app/views/locations/index.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Aktív?</th>
    </tr>
  </thead>
  <tbody>
    <% @locations.each do |location|  %>
    <tr>
      <td><%= link_to location.name, location_path(location) %></td>
      <td><%= location.is_active %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Új', new_location_path, class: 'uk-button'  %>

library/app/views/locations/new.html.erb
<div class="uk-container-center uk-panel uk-panel-box">
  <%= form_tag locations_path, method: :post, html: { class: 'uk-form' } do %>
      <div class="uk-text-center">
        <div class="uk-grid">
          <div class="uk-width-1-1">
            <div class="uk-form-row">
              <%= label_tag :name, 'Név:' %>
              <%= text_field_tag :name, 'Név' %>
            </div>
            <div class="uk-form-row">
              <%= label_tag :is_active, 'Aktív?:' %>
              <%= check_box_tag :is_active %>
            </div>
            <div class="uk-form-row">
              <%= submit_tag 'Tovább', class: 'uk-button'  %>
            </div>
          </div>
        </div>
      </div>
  <% end %>
</div>

library/app/views/locations/show.html.erb
<h1> A /<%= @location.name %>/ hely adatai </h1>

<div class="uk-container-center uk-panel uk-panel-box">
  <div class="uk-text-center">
    <div class="uk-grid">
      <div class="uk-width-1-1">
        <div class="uk-form-row">
          <%= label_tag :name, 'Név:' %>
          <%= label_tag :name, @location.name %>
        </div>
        <div class="uk-form-row">
          <%= label_tag :is_active, 'Aktív?:' %>
          <%= check_box_tag :is_active, nil, @location.is_active, disabled: true %>
        </div>
        <div class="uk-form-row">
          <%= link_to 'Szerkesztés', edit_location_path(@location), class: 'uk-button'  %>
        </div>
      </div>
    </div>
  </div>
</div>